/**
 * assetplex init 命令
 *
 * 初始化 ~/.assetplex/ 目录结构，生成模板文件
 *
 * 借鉴：
 * - agentsync 的 bundled skill 提示（init 时询问是否安装自带 SKILL）
 * - Claude Code 的 /init 命令
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { log } from '../../utils/logger.js';
import { getHubRoot, hubPath } from '../../utils/paths.js';
import { generateDefaultConfigToml } from '../../core/config.js';
import {
  PROFILE_TEMPLATE,
  COMMUNICATION_STYLE_TEMPLATE,
  TECH_STACK_TEMPLATE,
  CODING_STYLE_TEMPLATE,
  GIT_WORKFLOW_TEMPLATE,
  ENV_TEMPLATE,
  HUB_README_TEMPLATE,
} from '../templates.js';

export interface InitOptions {
  /** 强制覆盖已存在的目录 */
  force?: boolean;
  /** 从现有各工具反向导入 */
  importExisting?: boolean;
  /** 不显示交互提示 */
  yes?: boolean;
}

/** Hub 目录结构定义 */
const HUB_DIRECTORIES = [
  'identity',
  'skills',
  'rules/always',
  'rules/by-glob',
  'rules/by-project',
  'preferences',
  'mcp',
  'commands',
  'agents',
  '.backups',
];

/** Hub 初始文件定义（路径 -> 内容） */
const HUB_INITIAL_FILES: Array<{ path: string[]; content: string; overwrite: boolean }> = [
  {
    path: ['hub.toml'],
    content: generateDefaultConfigToml(),
    overwrite: false,
  },
  {
    path: ['README.md'],
    content: HUB_README_TEMPLATE,
    overwrite: false,
  },
  {
    path: ['identity', 'profile.md'],
    content: PROFILE_TEMPLATE,
    overwrite: false,
  },
  {
    path: ['identity', 'profile.auto.md'],
    content: [
      '<!-- AUTO-GENERATED by assetplex profile learn. Do not edit manually. -->',
      '# Auto-Learned Profile',
      '',
      '> 此文件由 \`assetplex profile learn\` 命令维护，记录 AI 从你的行为中学习到的事实。',
      '> 不要手动编辑此文件。运行 \`assetplex profile learn --dry-run\` 预览将要写入的事实。',
      '',
      '## 最近学习到的事实',
      '<!-- (尚无数据，运行 assetplex profile learn 学习) -->',
      '',
      '## 常用工作流',
      '<!-- (尚无数据) -->',
      '',
      '## 错误教训（Lessons）',
      '<!-- (尚无数据) -->',
      '',
    ].join('\n'),
    overwrite: false,
  },
  {
    path: ['identity', 'communication-style.md'],
    content: COMMUNICATION_STYLE_TEMPLATE,
    overwrite: false,
  },
  {
    path: ['identity', 'tech-stack.md'],
    content: TECH_STACK_TEMPLATE,
    overwrite: false,
  },
  {
    path: ['identity', 'env.md'],
    content: ENV_TEMPLATE,
    overwrite: false,
  },
  {
    path: ['preferences', 'coding-style.md'],
    content: CODING_STYLE_TEMPLATE,
    overwrite: false,
  },
  {
    path: ['preferences', 'git-workflow.md'],
    content: GIT_WORKFLOW_TEMPLATE,
    overwrite: false,
  },
  // 初始规则文件
  {
    path: ['rules', 'always', 'global.md'],
    content: [
      '# Global Rules',
      '',
      '> 此规则文件会同步到所有工具的 rules/always/，对所有 AI 助手始终生效。',
      '',
      '## 通用规则',
      '- 修改代码前先阅读相关文件',
      '- 不要做未被请求的改动',
      '- 不要添加未被请求的注释、文档或类型注解',
      '- 优先编辑现有文件，而非创建新文件',
      '- 简单优先，避免过度设计',
      '',
    ].join('\n'),
    overwrite: false,
  },
  // MCP 单源配置
  {
    path: ['mcp', 'mcp.sources.json'],
    content: [
      '{',
      '  "$schema": "https://json-schema.org/draft-07/schema",',
      '  "mcpServers": {',
      '    // 在此添加 MCP 服务器配置，assetplex 会自动同步到各工具：',
      '    // - Claude Code 的 ~/.claude.json',
      '    // - Codex 的 ~/.codex/config.toml [mcp_servers.x]',
      '    // - TRAE CN 的 ~/.trae-cn/mcp.json',
      '    // - WorkBuddy 的 ~/.workbuddy/.mcp.json',
      '  }',
      '}',
      '',
    ].join('\n'),
    overwrite: false,
  },
];

/**
 * assetplex init 实现
 */
export async function initCommand(options: InitOptions = {}): Promise<void> {
  const hubRoot = getHubRoot();

  log.info(`正在初始化 AssetPlex...`);
  log.info(`Hub 根目录: ${hubRoot}`);

  // 检查目录是否已存在
  if (existsSync(hubRoot) && !options.force) {
    // 检查是否有 hub.toml
    const hubTomlPath = hubPath('hub.toml');
    if (existsSync(hubTomlPath)) {
      log.warn(`Hub 已存在：${hubRoot}`);
      log.warn(`如需重新初始化，请使用 --force 选项`);
      return;
    }
  }

  // 创建目录结构
  log.info('创建目录结构...');
  for (const dir of HUB_DIRECTORIES) {
    const dirPath = resolve(hubRoot, dir);
    mkdirSync(dirPath, { recursive: true });
    log.debug(`  创建目录: ${dir}`);
  }

  // 写入初始文件
  log.info('写入模板文件...');
  let createdCount = 0;
  let skippedCount = 0;
  for (const file of HUB_INITIAL_FILES) {
    const filePath = resolve(hubRoot, ...file.path);
    if (existsSync(filePath) && !file.overwrite && !options.force) {
      log.debug(`  跳过已存在: ${file.path.join('/')}`);
      skippedCount++;
      continue;
    }
    writeFileSync(filePath, file.content, 'utf-8');
    log.debug(`  写入文件: ${file.path.join('/')}`);
    createdCount++;
  }

  log.success(`AssetPlex 初始化完成！`);
  log.info(`  根目录: ${hubRoot}`);
  log.info(`  创建文件: ${createdCount} 个`);
  if (skippedCount > 0) {
    log.info(`  跳过已存在: ${skippedCount} 个`);
  }

  // 显示后续步骤
  log.info('');
  log.info('下一步：');
  log.info('  1. 编辑 ~/.assetplex/identity/profile.md 填写你的个人画像');
  log.info('  2. 运行 `assetplex doctor` 检测各 AI 工具安装状态');
  log.info('  3. 运行 `assetplex sync` 同步到所有工具');
  log.info('  4. 运行 `assetplex --help` 查看所有命令');
}
